package com.eperformax.japsrequest.response

data class Data(
    val androidEligibleRegistrationVersion: Int,
    val androidIntentURL: String,
    val bankAccounts: Any,
    val bankWiseSuccessRate: Any,
    val centralMapperDetails: Any,
    val deRegistered: Boolean,
    val deviceBindingAttemptsOnCurrentDeviceId: Int,
    val hasUsedAxisBefore: Boolean,
    val homePagePromotionList: List<HomePagePromotion>,
    val iosEligibleRegistrationVersion: Int,
    val lastDeviceBindingTimestamp: Any,
    val loginResponse: Any,
    val mandatesEligible: Boolean,
    val matchedDeviceId: Any,
    val p2mMccNotAllowedOnCCList: List<String>,
    val p2mVpaNotAllowedOnCCList: List<String>,
    val payGenericURL: String,
    val pendingRequestsCount: Int,
    val platformWiseData: PlatformWiseData,
    val ppi: Any,
    val registered: Boolean,
    val registrationEligibility: RegistrationEligibility,
    val registrationStatus: String,
    val tokenExpiryTimeInDays: Int,
    val udirEnabled: Boolean,
    val upiConfiguration: UpiConfiguration,
    val upiIntentAppSelectionDetails: UpiIntentAppSelectionDetailsX,
    val upiOnCCFlag: Boolean,
    val upiOnCreditLineFlag: Boolean,
    val upiPreferences: UpiPreferences,
    val vpas: List<Vpa>
)